# Tesseract configuration file

name: "pymapdl_tess"
version: "0.0.1"
description: "Evaluate compliance using the SIMP material model"

build_config:
  extra_packages:
  - "build-essential"
  - "libgl1"
  - "libxrender1"
